FROM openjdk:8
ADD target/demo-docker.jar demo-docker.jar
EXPOSE 8086
ENTRYPOINT ["java", "-jar", "demo-docker.jar"]
#FROM tomcat:alpine
#COPY *.war /usr/local/tomcat/webapps/
#COPY tomcat-users.xml /usr/local/tomcat/conf/
#COPY manager.xml /usr/local/tomcat/conf/Catalina/localhost/
#EXPOSE 8086